name: API TEST RUNNER

on:
  schedule:
    - cron: '0 6 * * *'
  pull_request:
    branches: [main]
  workflow_dispatch:

  workflow_call:

jobs:
  run-tests:
    name: Run Tests in ${{ github.event.inputs.environment || 'specified environment' }} for commit ${{ github.event.inputs.commit || 'latest commit' }}
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:latest
    env:
      NODE_ENV: 'staging'
      BASE_URL: ${{ github.event.inputs.environment || secrets.BASE_URL || 'https://staging.blackbirdailabs.com/' }}
      COMMIT: ${{ github.event.inputs.commit || 'latest commit' }}
      COMMIT_INFO_MESSAGE: ${{ github.event.head_commit.message }}
      COMMIT_INFO_EMAIL: ${{ github.event.head_commit.author.email }}
      COMMIT_INFO_AUTHOR: ${{ github.event.head_commit.author.name }}
      COMMIT_INFO_TIMESTAMP: ${{ github.event.head_commit.timestamp }}
      COMMIT_INFO_REMOTE: ${{ secrets.GITHUB_SERVER_URL }}/${{ github.repository }}
    timeout-minutes: 120
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run Playwright tests
        id: run-playwright-tests
        shell: bash
        run: |
          echo "DATA=${{ github.event.head_commit.message }} ${{ github.event.pull_request.head.sha }} ${{ env.COMMIT_INFO_AUTHOR }}"
          cat $GITHUB_EVENT_PATH | jq .
