name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runner_name: [ "Runner 1", "Runner 2" ]
        shard: [1/2, 2/2]
        include:
          - runner_name: "Runner 1"
            shard: 1/2
          - runner_name: "Runner 2"
            shard: 2/2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set runner name based on shard
        run: |
          echo "RUNNER_NAME=${{ matrix.runner_name }}" >> $GITHUB_ENV
          echo "SHARD=${{ matrix.shard }}" >> $GITHUB_ENV
          echo "CURRENTS_MACHINE_ID=${{ matrix.runner_name }}" >> $GITHUB_ENV

      - name: Log runner name
        run: |
          echo "This job is running on $RUNNER_NAME"
        env:
          RUNNER_NAME: ${{ matrix.runner_name }}
          CURRENTS_MACHINE_ID: ${{ matrix.runner_name }}

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        env:
          RUNNER_NAME: $RUNNER_NAME
          CURRENTS_MACHINE_ID: $RUNNER_NAME
        run: npx pwc --key KPEvZL0LDYzcZH3U --project-id WeZwSj --ci-build-id ${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt}} --shard $SHARD

    # - name: Run commit info
    #   run: yarn ts-node ./src/commit-info-test.ts
