name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Install dependencies
      run: npm install
    

    - name: Run Playwright tests
      run: CURRENTS_API_URL=https://cy-staging.currents.dev npx pwc --key AcceNBS8GCEFdr4C --project-id ghc2jY --ci-build-id ${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt}}

    # - name: Run commit info
    #   run: yarn ts-node ./src/commit-info-test.ts