name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1/6, 2/6, 3/6, 4/6, 5/6, 6/6]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Install dependencies
      run: npm install
    

    - name: Run Playwright tests
      run: CURRENTS_API_URL=https://cy-staging.currents.dev npx pwc --key AcceNBS8GCEFdr4C --project-id ghc2jY --ci-build-id ${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt}} --shard ${{ matrix.shard }}

    # - name: Run commit info
    #   run: yarn ts-node ./src/commit-info-test.ts