name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}  # Pass the generated matrix as an output
    steps:
      - name: Set number of shards
        id: set-shards
        run: echo "SHARDS=3" >> $GITHUB_ENV  # Change this to the desired number of shards

      - name: Generate matrix
        id: set-matrix
        run: |
          SHARDS=${SHARDS:-2}  # Default to 2 shards if not set
          MATRIX=$(seq 1 $SHARDS | jq -R '[inputs | {runner_name: ("MyRunner " + .), shard: (. + "/" + "'$SHARDS'")}]')
          echo "matrix=$MATRIX" >> $GITHUB_ENV
          echo "::set-output name=matrix::$MATRIX"  # Set output for the next job
        env:
          SHARDS: ${{ env.SHARDS }}

  playwright-tests:
    needs: generate-matrix 
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.generate-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        env:
          CURRENTS_MACHINE_ID: ${{ matrix.runner_name }}
        run: npx pwc --key KPEvZL0LDYzcZH3U --project-id WeZwSj --ci-build-id ${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt}} --shard ${{ matrix.shard }}

    # - name: Run commit info
    #   run: yarn ts-node ./src/commit-info-test.ts
